version: '3'
services:
  python:
    build:
      context: ..
      dockerfile: .devcontainer/python/Dockerfile
    container_name: python
    working_dir: '/root/src'
    tty: true
    volumes:
      - ../src:/root/src
    command: "python /root/src/DiscordMusicBot2.py"